name: Deploy Website

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 137.184.42.115
          username: root
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            /var/www/deploy.sh
